sudo: required

language: c

services:
  - docker

before_install:
  - make

script:
- 


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push containerlisp/lisp-10-centos7;
    fi
  - echo All done.
