sudo: required

language: c

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::7}
     - REPO=containerlisp/lisp-10-centos7

services:
  - docker

before_install:
  - make

script:
- 


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      TAG=$(date -d $(grep http://beta.quicklisp.org 1.0/root/opt/app-root/install.lisp | awk -F'/' '{ print $6 }') +%Y%m%d).$TRAVIS_BUILD_NUMBER;
      docker tag $REPO:latest $REPO:$TAG;
      docker tag $REPO:latest $REPO:$COMMIT;
      docker push $REPO:latest;
      docker push $REPO:$TAG;
      docker push $REPO:$COMMIT;
    fi
  - echo All done.
